### ISSUE TITLE
Would you consider publishing Arm binaries?

### ISSUE THREAD

**Issue by alexellis** [atuinsh/atuin#1032]
Hey @ellie 

Would you consider publishing Arm binaries for Darwin and 64-bit Linux?

We realised you didn't have enough time to get to adding this tool to arkade, so someone from the community has picked it up.

They had a query about Arm binaries - so for now we can only add amd64 for Linux/Darwin:

https://github.com/alexellis/arkade/pull/925

Thoughts?

Alex

**Comment by r-darwish** [comment]
Hi there!
I managed to build atuin for aarch64 on an amd64 machine using [this docker image](https://github.com/rust-cross/rust-musl-cross). I think it's worth checking out.

Thank you for this project!

**Comment by Lugoues** [comment]
I was able to fix this by adding `libc6-dev-arm64-cross`	to the pre-reqs but generating completions fails now. 
See: https://github.com/Lugoues/atuin/actions/runs/5251234999/workflow#L57

**Comment by mcompton13** [comment]
The MacOS ARM build is failing generating completions as well, similar to the linux ARM build after Lugoues' fix. I believe the issue is that the build is cross compiling ARM binaries on x86 CPUs and then the completions are generated by running the `atuin` binary that was just compiled for ARM. Turns out x86 CPUs can not execute ARM binaries :stuck_out_tongue_winking_eye:.

One option would be skip generating completions for the ARM builds, which seems like the quickest solution.

Another option would be to also compile x86 version of `atuin` in the ARM builds and use that to generate completions.

I also saw [this plugin](https://github.com/marketplace/actions/run-on-architecture) that would work for emulating ARM CPUs on x86 hardware, but I think that would only work for the Linux ARM build.

**Comment by ellie** [comment]
> The MacOS ARM build is failing generating completions as well, similar to the linux ARM build after Lugoues' fix. I believe the issue is that the build is cross compiling ARM binaries on x86 CPUs and then the completions are generated by running the `atuin` binary that was just compiled for ARM. Turns out x86 CPUs can not execute ARM binaries 😜.
> 
> One option would be skip generating completions for the ARM builds, which seems like the quickest solution.
> 
> Another option would be to also compile x86 version of `atuin` in the ARM builds and use that to generate completions.
> 
> I also saw [this plugin](https://github.com/marketplace/actions/run-on-architecture) that would work for emulating ARM CPUs on x86 hardware, but I think that would only work for the Linux ARM build.

I appreciate that there is a nice workaround, but I'd rather wait until we can compile and run ARM end-to-end correctly. 

I may end up just using ARM runners, as the issue with all workarounds is that they work right up until we need to use some package that touches native code a little more than usual, or similar. Until it's native, ARM builds will be brittle, and I'd rather only commit to building ARM when we can commit to it being a good standard.

**Comment by ellie** [comment]
Interestingly, @alexellis (OP) has a company doing exactly what we need! https://actuated.dev/

I'll check it out later this week and maybe get this closed out 🙏

**Comment by ellie** [comment]
Resolved as of #1133! I bought a refurbed M1 mini and have it running builds under my desk 😂 

It happens to run builds much much faster than shared GitHub runners, which is lovely! I'll upload binaries to v15, and all future releases should have them automatically.

(limited network access and a bunch of other things, but hopefully there's a real solution at some point that isn't $$$$)

**Comment by willifehler** [comment]
Thanks a lot Ellie. Great news. I guess the install scripts needs an update to pick the right asset if the arch is aarch64?

**Comment by alexellis** [comment]
@ellie I emailed you back, but didn't get a reply. When you're less busy I was curious to hear back from you.
