### ISSUE TITLE
`atuin sync --force` does not download everything

### ISSUE THREAD

**Issue by arcuru** [atuinsh/atuin#1150]
So this is..a little odd, and probably my fault somehow.

My history database on the default sync server somehow has ~80 records that have the same `(timestamp, cwd, command)`, but different `id`s. That triplet is [required to be unique in the local mysql database](https://github.com/atuinsh/atuin/blob/main/atuin-client/migrations/20210422143411_create_history.sql#L12), so I don't know how that happened. All the dupes happened in mid-October 2022.

The dupes seem to have come from a single session when I had been doing some development work on a different project. There's a group of commands where most, but not all, commands just show up twice. I've already dumped my full list of commands stored on the sync server to potentially investigate further.

It causes a lot of problems with syncing because my local history count is missing those commands while the server has them. Due to [this check](https://github.com/atuinsh/atuin/blob/2b1d39e270cb28e68403ba1a909378a6920b2208/atuin-client/src/sync.rs#L147) none of my machines will upload new commands until they have more local history than that count of 80.

I can easily repro on the v15 release (or v16) by:
```
$ rm -rf ~/.local/share/atuin # remove existing install
$ atuin login
Please enter username: patrick
Please enter encryption key [blank to use existing key file]: <snipped>
Please enter password:
Logged in!

$ atuin sync --force; atuin status
Sync complete! 37841 items in database, force: true
[Local]
Sync frequency: 10m
Last sync: 2023-08-03 21:46:29.433261161 UTC
History count: 37841

[Remote]
Address: https://api.atuin.sh
Username: patrick
History count: 37920
```

I think the only way for my account to recover from this situation is by dropping my history table on the server so that I can resync good data from my local copies.

**Comment by patricksjackson** [comment]
Yep, this was my fault.

Dug through the command logs a bit more, this happened because I imported history from fish, and was messing with the Atuin sync at the same time.

It looks like I did the following:
1. Imported history from fish
2. Logged in and synced that to the Atuin server.
3. Removed my local install for some reason.
4. Imported from fish again.
5. Reconnected and uploaded the new stuff to the server.

The only way I can think to stop somebody else doing this to themselves is by reworking the sync code in the client to remove dupes before uploading, preferring the history entries already on the server.

**Comment by benjaminwood** [comment]
I had this problem too and it really perplexed me for a while (months 😬). I'm not sure how commonly people run into this, but when it happens it's very mysterious because sync appears to be delayed. Would be better if an error/warning was raised so ppl know they really do have a problem that needs to be fixed.

**Comment by ellie** [comment]
@benjaminwood did you also do the sequence of things that arcuru mentions above?

Fwiw, this + a whole bunch of other sync oddities should not occur with sync v2 - currently opt in, and on `main`. It's much faster + testing so far seems to have less edge cases

**Comment by benjaminwood** [comment]
@ellie I'm honestly not sure how I ended up in the situation. It's very possible that I followed the same path as arcuru.

Great to hear regarding Sync v2! Perhaps this can simply be closed when v2 is made the default.

Thanks for you work on Atuin! I'm a big fan. I use it to persist history in ephemeral development environments such as VS Code's remote-containers and GitHub Codespaces.

**Comment by ellie** [comment]
I'm gonna close this, now that sync v2 is the default for new installs :D
