### ISSUE TITLE
Can I reset the password?

### ISSUE THREAD

**Issue by yusef-ho** [atuinsh/atuin#1183]
Hello,
I installed self-hosted atuin couple months ago, and tried a little bit.
but after I was busy and reinstalled my OS.
I searched issues and documents for 2 hours, but i couldn't find any method to retrieve password.
Can I retrieve/reset password from server side?

**Comment by ellie** [comment]
Unfortunately not - if you lose the keys for your account, you'll need to open a new one. We generate an encryption key for your data, which is only stored on your client - if you don't have a backup of this, your data is gone

We can't provide access to your data, because we do not have access to it ourselves.

**Comment by yusef-ho** [comment]
@ellie Thank you.
I have the key, but i forgot password. What can I do?
