### ISSUE TITLE
Working remotely

### ISSUE THREAD

**Issue by mrwilby** [atuinsh/atuin#1214]
Thanks for creating a useful tool.

Perhaps my use case is a little odd, but when I am working remotely, my self-hosted server endpoint is not available. This means that when the tool attempts to periodically sync, I see panics:

`
Error: error sending request for url (https://domain.com/sync/status): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known
                  Caused by:
                               0: error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known
                               1: dns error: failed to lookup address information: nodename nor servname provided, or not known
                               2: failed to lookup address information: nodename nor servname provided, or not known
                               Location:
                               /private/tmp/atuin-20230807-5737-1yn4qa1/atuin-16.0.0/atuin-client/src/api_client.rs:140:20
`

Not sure what the best way of handling this is, since ordinarily this would be something most users might want to know about, but in my case, this is totally expected and not something that causes concern.

Would it be possible, in the future, to have a way to disable such warnings/panics and perhaps only report the issue if the connection cannot be made within a certain configurable period of time ? For example, if I am offline and the server is unreachable for longer than a few days, then begin to notify the user of a connection issue?

**Comment by ellie** [comment]
> Thanks for creating a useful tool.

No worries! 😊 

Not so odd, this should work. This is printed to your shell at an interval, when you're not using Atuin?

What shell are you using?

**Comment by mrwilby** [comment]
Thank you. I am using nushell. 

It is not printed when I am not using Atuin. It seems to happen after I initiate a potentially long-running command (e.g. compiling some code) and then, at the very end of the command, I see this error message once the command completes.

If I run a single command that doesn't take much time, then I don't see this error (e.g. a normal "ls" or something similar).

**Comment by mrwilby** [comment]
Actually, now that I write the above, it's even happening after a short-running command (like "ls"). So not sure exactly what the trigger is. But it happens after the command.

I have a fairly short sync interval defined - 30s in my config file.

I will try to keep observing and see if I can figure out the pattern.

**Comment by dcarosone** [comment]
It won't be the time taken by the command, it will be the time since atuin was last invoked (by the last command, in any shell on the machine) to check for sync status.

> I have a fairly short sync interval defined - 30s in my config file.

That really is quite short. One thing to note that might make you more comfortable with a longer setting - this is only the time needed for sync between machines (via the server). Multiple shells on the same machine are synced via the local sqlite db at all times.  So you really only need regular syncing if you're paranoid about backing up your precious history even if the machine blows up at any time, or if you're very regularly wanting commands on one machine to appear on another.

As far as enhancements go:
* I agree a warning makes more sense when there hasn't been a sync in some longer time than a single (or a few) sync periods.
* an exponential backoff might be worthwhile to avoid too many attempts when offline
* #54 would be really useful here and in other related cases where not all hosts can see the same sync server, maybe ever.

**Comment by mrwilby** [comment]
I have it set as a short sync interval so I can sync command histories between my local machines when I'm working at home. However, if I'm working remotely then obviously syncing won't work. When working remotely, I'd be happy if the error could be swallowed so there was no output at all, but that might lead to issues when a user expects the sync to work (i.e. I'm working "at home" in my situation) and the sync is not functioning for some reason. This is why I suggested perhaps showing a warning if syncing is not working. Some configurability around all this would likely be needed in case people want to see an error message after every failed sync.

**Comment by arcuru** [comment]
The [nushell hook script](https://github.com/atuinsh/atuin/blob/7a914221a7c9fb4b5322aa3c391cb9ad1709c866/atuin/src/shell/atuin.nu#L23C81-L23C81) doesn't redirect stderr on that sync command, even though the other shell scripts do. So only nushell users will ever see that error today. I think it's safe to assume we can ignore it during the background sync.

@mrwilby - you can start ignoring this error today by editing your [~/.local/share/atuin/init.nu](https://atuin.sh/docs/advanced-install#nushell) script with the changes in #1320
