### ISSUE TITLE
Unclear error messages on sync failure

### ISSUE THREAD

**Issue by grimreaper** [atuinsh/atuin#1233]
**Describe the bug**
When running `atuin sync` an error occurs. Ideally we fix this, but at least I should get a meaningful error describing the problem.

**To Reproduce**

```

∴atuin sync -f
Error: error decoding response body: EOF while parsing a value at line 1 column 0

Caused by:
    EOF while parsing a value at line 1 column 0

Location:
    atuin-client/src/api_client.rs:246:21
```

**Device (please complete the following information):**
 - OS: macOS 13.5.2 (22G91)
 - Shell zsh 5.9 (x86_64-apple-darwin22.1.0)

**Additional context**

It is possible I forgot my username or password.

**Comment by ellie** [comment]
Yeah our errors do need improving

Could you provide some more information about what you did before running sync? Did you register, do you have any history imported?

Or did you install and then immediately run `atuin sync -f`?

**Comment by ellie** [comment]
Oh also are you self hosting?

**Comment by ellie** [comment]
> Unfortunately I had forgotten the username+password

If you've forgotten the username and password, I'm not sure how you would have logged in on the new machine. Are you able to summarize anything else you may have done?

In order to sync, you need to know:

1. Your username
2. Your passwrod
3. Your encryption key

Without those, I'm afraid you will need a new account.
