### ISSUE TITLE
Time of last-run command can be wrong (now instead of actual)

### ISSUE THREAD

**Issue by dcarosone** [atuinsh/atuin#1261]
**Describe the bug**
The time for the most-recent command is often wrong. It shows basically now rather than the actual time. 

**To Reproduce**
1. Start a shell, run some commands; maybe use `date` as the last.
2. leave the shell idle for a while
3. hit return (an empty command)
4. hit up-arrow or ctrl-R to see command history
5. last command shows as Xms then 1s ago, counting up

**Expected behavior**
Time of commands should be the time they were run and entered into history

**Error logs**

**Device (please complete the following information):**
 - OS: NixOS-unstable
 - Shell: bash
 - Version: `16.0.0`

**Comment by conradludgate** [comment]
Ah. I suspect that the history id isn't being cleared properly

**Comment by dcarosone** [comment]
If so could this be common cause for #1039 ?

**Comment by dcarosone** [comment]
This still seems to be happening for me on 17.0.1 (bash on nixos).  I will check nu.

**Comment by dcarosone** [comment]
It is not happening in nu.

And step 3 (the empty command) doesn't seem to be needed anymore, it happens all the time.

It could be an interaction with starship and/or direnv, which i also have installled?  Bash hooks are fun.

**Comment by arcuru** [comment]
It's a bug in bash-preexec. When you open the atuin interactive search it runs the preexec hooks before that opens, and it uses the argument as the last command you ran. It's basically telling atuin "we're running the 'date' command again" and then it opens the atuin history.

Atuin is seeing that you ran that exact command twice and showing you the time since the most recent, which was right when you opened the interactive search.

I added a note in the Atuin readme that bash-preexec has this sort of issue, though I didn't fully explain it.
