### ISSUE TITLE
Commands executed via enter_accept from history can't take input

### ISSUE THREAD

**Issue by mjpieters** [atuinsh/atuin#1372]
**Describe the bug**

When I complete a command from history, and that command asks for input from stdin, I can't actually give that input. Nothing happens when I type and the program receives no input.

**To Reproduce**

Assuming you have Python installed, this is a short and easy demonstration of the problem:

1. If you are an existing user, enable `enter_accept` first
2. Start a fresh shell
3. Execute the following short line of bash: `bash -c 'read -p "Say something? " tosay; echo "Say: $tosay"'`, enter something to be echoed back.
4. Recall the command, hit `<TAB>` and then enter to execute it again. It still works the same.
5. Recall the command and hit enter to execute it immediately. The `Say something? ` prompt runs but no input can be given any more.

If you remove the `bash -c '...'` wrapper and execute the commands directly in the current shell, then the above reproducer can't be interrupted either. You'll have to kill that shell from another session.

**Expected behavior**

`enter_accept` should not leave the environment in a broken state where input isn't possible.

**Device (please complete the following information):**
 - OS: Linux
 - Shell bash
 - Version v17.0.1

**Comment by danwilliams** [comment]
I can confirm the same here. The workaround is to use `TAB` to populate the command into my prompt buffer for editing, and then hitting `ENTER` works fine to run it normally. If `ENTER` is used from the Atuin interface, any input requested seems disconnected. For instance try with something simply like `rm` or `cp`, and the prompts will appear but you won't be able to response to them.

**Comment by arcuru** [comment]
The reason this happens is because on bash, to make the `enter_accept` feature work, we need to run the command ourselves from inside of the function bound to a keybinding. It turns out that functions run by keybindings can't accept any input without modifying the recalled commands.

e.g. If the function you're recalling is "echo -n "Say something: "; read -e tosay; echo $tosay" it will work, though the output will be a bit messed up.

It works in the other shells because they have builtin functions to accept a given command and run it themselves, but for bash we have to run the command ourselves using inside the keybinding eval.

I put together a set of fixes that would improve the feature for bash, but would not fix this problem. I'm proposing that we disable `enter_accept` by default for bash until there's a fix.

**Comment by ellie** [comment]
Ugh this was auto-closed by GitHub.

It wasn't "fixed", but we've disabled enter-accept with bash for now. It doesn't look like it's possible to implement in bash, though if that changes we will enable it again.

**Comment by mjpieters** [comment]
So how does a command like `env` manage to run a command for you? It doesn't show these issues but must itself execute the command you give it, directly.

E.g. the reproducer, with `env` prefixed to run it via that command:

```sh
env bash -c 'read -p "Say something? " tosay; echo "Say: $tosay"'
```

works just fine when executed using `env`. Or is this specific to how bash handles keybindings? 

If not, I'd study the [`env` source code](https://github.com/coreutils/coreutils/blob/60bd7bad9d2473d2bd0462a1cbe05144c35ad557/src/env.c#L175) to see what that command does to ensure interactive commands continue to work.
