### ISSUE TITLE
FEATURE REQUEST: atuin update subcommand

### ISSUE THREAD

**Issue by AtomicRobotMan0101** [atuinsh/atuin#1461]
Currently one must use `apt update` or the script located on the Atuin site to update.

Perhaps add `atuin update` as a subcommand, which fires off the script?

**Why?**

I'm using Mint Cinnamon and the apt for the last update (17.1) is still reporting 17.0.1

When I use Atuin history, it is advising me at the top that an update is available. It **irks** me that I have to go to the site each time to retrieve the name of the script.... irksome! :)

**Comment by arcuru** [comment]
> Currently one must use apt update or the script located on the Atuin site to update.

I just wanted to point out that `apt update` will never do anything to Atuin, because Atuin is not available in the Debian repos. The install script installs the .deb file produced by the CI in this repo.

The install script hides the actual install process, so it leads to this confusion. I question whether it's a good idea to make it easier for a user to use this script to manage their install, but I suppose that might make it easier to keep people with non-standard installs up to date.

The real fix for your issue is to get Atuin packaged in the debian package repo. [The most recent attempt I can find](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1036165) has stalled.

**Comment by ellie** [comment]
> It irks me that I have to go to the site each time to retrieve the name of the script.... irksome! :)

You could retrieve it from your shell history ;)

But on a more serious note. I agree with what @arcuru said about it not being a great idea to write scripts to manage installs, beyond what we already have. It might be a good idea to make it clearer which underlying mechanism we have used to install Atuin, so that the user can continue to use that to stay up to date 

Otherwise, if we wanted to go all the way, something like this may work: https://github.com/jaemk/self_update

But would certainly have issues with system package managers. So we'd probably want to set a flag upon install, to indicate if it's a package-manager managed install or one where Atuin can keep itself up to date

**Comment by AtomicRobotMan0101** [comment]
Understood :) I love this project and was thinking that this may be an improvement.

Consider it closed!
