### ISSUE TITLE
how to unistall 

### ISSUE THREAD

**Issue by AugustinMauroy** [atuinsh/atuin#1485]
i had install attuin to test it but I din't need it. So how to uninstall it.

**Comment by arcuru** [comment]
Well, you should uninstall it using the same method you installed it, and then remove the atuin specific lines from your shell init script.

If you used the install script here, it may have installed from your package manager or by using `cargo install`. You should uninstall it using the method it was installed with. The install script will have printed output that told you how it was installing it.

Since you haven't specified your OS, package manager, or shell, I can't help you any further than that.

**Comment by AugustinMauroy** [comment]
I use MacOS, and I use simple shell command provided by the website

**Comment by binary-signal** [comment]
which command did you use specifically  ?

**Comment by ellie** [comment]
If you used the install script, and you're using macOS, you _probably_ want to run

```
brew uninstall atuin
```

and then remove the Atuin line from your `.zshrc`

We may want to add an install script that does the reverse, or maybe just make it an arg on the script.

**Comment by AugustinMauroy** [comment]
@binary-signal 

```
 bash <(curl --proto '=https' --tlsv1.2 -sSf https://setup.atuin.sh)
 ```

**Comment by binary-signal** [comment]
**Assuming you run ubuntu and used the default install options**

To uninstall atuin 

First run
```shell
sudo  dpkg --purge atuin # purge will remove the configuration too let's hope.
```

Then delete the following folders, just in case --purge command has left leftovers behind.
```shell
rm -rf ~/.config/atuin
rm -rf ~/.local/share/atuin
```

Finally, you need to remove from .zshrc or .bashrc or (insert your shell config file) the line added by atuin, 
example for zsh config file
```shell
# file: .zshrc
bla bla bla
bla bla bla 
....
atuin init zsh #  delete this line, save changes, relaunch shell
```

That's all.
