### ISSUE TITLE
Feat: Allow combining search methods (ex Session + Directory)

### ISSUE THREAD

**Issue by Jelloeater** [atuinsh/atuin#1611]
This would allow you to have a similar search history as global, but to not allow command history from other sessions.

Ex
Session 1:
git checkout -b feat/xxx

Session 2:
git checkout -b feat/xx2

It would be easy to accidentally hit the wrong entry and end up with at least the wrong Git branch if you use Global.
I figure this could save some folks some serious headaches down the road.
Maybe make it a custom mode you can toggle to?
Showing what combination of options in the bottom left would be nice as well.

**Comment by ellie** [comment]
Hey! We're unlikely to go in this direction - with the search and filter modes we have at the moment, things are already a little complicated. Adding combinations there will be an explosion of complexity that makes things harder for users to reason about + for us to implement a smooth UX for

For the specific example you mention here, I think `workspaces` would work nicely for you. This limits your search history to the current `git` repo

Otherwise, would tags solve your problem? There's a discussion here about what they could be: https://forum.atuin.sh/t/feature-idea-taggable-environments-to-group-shell-commands/76/11

**Comment by Jelloeater** [comment]
... wow, I think the workspace filter is exactly what I was looking for, to separate git / project specific commands!You guys ROCK! <3
GL on the tag feature, that might help too. I've been telling all my dev friends about the project and they love it!

**Comment by Jelloeater** [comment]
... wow, I think the workspace filter is exactly what I was looking for, to separate git / project specific commands!
You folks ROCK! <3
GL on the tag feature, that might help too. I've been telling all my dev friends about the project and they love it!
