### ISSUE TITLE
Make format for history configurable

### ISSUE THREAD

**Issue by asgeirn** [atuinsh/atuin#1616]
I often forget which directory I ran a command from, and when I then find `./start.sh` in my history I'm only halfway there.

With the help of #619 I can find the directory, but I'd like this config:

`history_format` -- default format for `atuin history list`

**Comment by ellie** [comment]
I'm not sure what this issue is asking for, and why `--format` does not achieve what is required. 

Happy to open an issue for implementing this if it's definitely required, but we should be able to achieve this with an alias

```
alias myhistory="atuin history list --format 'blah'"
```

> I might even like to have the second column actually be relative time, but the timestamp most certainly must be present...

This is exactly what the `{time}` part of the format arg does. It prints the timestamp, not the relative time.

For example

```
atuin history list --format "{time} - [{duration}] - {directory}$\t{command}"
```

**Comment by asgeirn** [comment]
I agree that an alias would perfectly solve this, this is merely a request to achieve the same without the need to create an alias.

Much in the same way as I have this in `.gitconfig` to modify what `git log` does by default:
```
[format]
        pretty = format:%C(yellow)%h %C(cyan)%>(12)%ad %Cgreen%<(7)%aN%Cred%d %Creset%s
```

**Comment by ellie** [comment]
@ylluminate could you open a separate issue please? This issue is not about the TUI format, it's about the CLI history list.

>  this is merely a request to achieve the same without the need to create an alias.

Makes sense. I'd just like to make sure we aren't adding config for things that aren't trivially solvable in other ways. 

I'd very happily review + merge a PR for this, but am unlikely to prioritise the work myself
