### ISSUE TITLE
Rebinding up arrow key to down arrow key

### ISSUE THREAD

**Issue by patriksvensson** [atuinsh/atuin#1621]
Ok, this might sound strange, but is there any way to reconfigure "up arrow" key to be "down arrow" key instead?

Great job with Atuin btw. I really like it!

**Comment by ellie** [comment]
> Great job with Atuin btw. I really like it!

Thank you! 🙏 

I'm not sure if you mean for opening Atuin, or for navigation in the TUI

### For opening Atuin

There's nothing built in for configuring the up arrow -> down array trigger. Really, this is a shell binding.

You can see an example for zsh here: https://docs.atuin.sh/configuration/key-binding/#zsh - you could use bindkey for down arrow there

### For tui navigation

The closest to this would be inverting the TUI, I guess. `invert = true` in your config. Though it's not quite what you want

Otherwise, we have an issue for key binding here #193, and are slowly making progress towards it

**Comment by patriksvensson** [comment]
@ellie It was the key binding for opening Atuin I was looking for, and after reading the docs it makes sense. Thanks!

Keep up the good work!
