### ISSUE TITLE
Documentation: explain what style = "auto" does

### ISSUE THREAD

**Issue by djc** [atuinsh/atuin#1680]
I just switched from the default to `compact` (which I think I prefer), and it seems curious that the code defines `auto`, `full` and `compact` but doesn't describe what `auto` does (it seems to select `full` always from what I've seen).

**Comment by ellie** [comment]
> I just switched from the default to compact (which I think I prefer)

Me too! I'm thinking of making it the default someday, but just need more data on what people use/prefer

Auto will switch from full -> compact when the window's height becomes too small for the UI to display properly. I think it was originally implemented because someone preferred compact in their IDE terminal, but full elsewhere.

I've updated the docs now, thanks for prompting 🙏
