### ISSUE TITLE
Troubleshooting sync

### ISSUE THREAD

**Issue by jbellis** [atuinsh/atuin#1702]
I have atuin installed on two hosts.  Both of them think they are logged in to the default sync server.  One says there is 15k entries in the history, the other says 3k.

As a starting point I think it would be useful to have a way to verify what account you are logged in as.

**Comment by ellie** [comment]
Hey! Thank you for sponsoring ❤️ 

Firstly, running `atuin status` will show details about your account + the remote server. Including your account username. I need to update the docs, sorry.

Otherwise, you can run any Atuin command with ATUIN_LOG=debug to get much more output. It will be _very_ chatty.

Some first things to try though

## If using the old sync

Just try `atuin sync -f` on both hosts (if you haven't already), lmk if that resolves anything

I would recommend trying the new sync if you're having any issues though.

Put 

```
[sync]
records = true
```

In the bottom of your Atuin config, then run `atuin sync`. It will probably prompt you to run `atuin history init-store`, do so if asked.

More info: https://forum.atuin.sh/t/sync-v2-testing/124/13

## If using the new sync

Please share the output of `atuin store status`

**Comment by hrfried** [comment]
Upgrading server/clients to 18.0.1 and using sync v2/associated CLI commands seems to have fixed this issue for me as well. Just for reference, running with postgres on an rpi4 with server and most clients installed/updated with cargo (and a couple clients using package managers or manual package installs).

One thing I realized was that I (probably more than once) forgot to restart the systemd service for the server after updating, and that may have actually been what screwed up my sync in the first place. Easy to forget the server and client technically run from the same binary, and I'm pretty sure with a basic service, systemd will keep chugging along using the binary it loaded into memory when the service started.

I think it should be possible to create an associated systemd `atuind.path` to restart the service if `/path/to/atuin/binary` changes. Might just be a me problem, but putting it here in case it's useful.

**Comment by jbellis** [comment]
Switching both machines to sync v2 fixed my problem.

**Comment by martinetd** [comment]
Same here had problems with v1 -- first syncs didn't work at all, then with --force I got some history up to a point and no history would be shared after that even when trying force syncagain on both ends.

switching to v2 I now get new commands properly shared, but there's still a hole after v1 stopped working where each machine has history on its end but not the other one's. `atuin store verify` is also all OK on both machines.

`store status` lists new commands so it's not quite enough to debug further what happened to records in the middle here, but I'm not sure it's worth looking that much further -- I'll just reimport the history from bash on both ends; please just take that as an endorsement that sync v2 is already better than the old one :)
If there's something I could check before nuking the bugged local atuin directories though feel free to ask.

**Comment by ellie** [comment]
Looks like sync v2 solved the issues here - I'll close it. Thanks everyone!

With 18.2, sync v2 is the default for new installs. I'll make it the default for everyone soon
