### ISSUE TITLE
Error: migration 20230619235421 was previously applied but is missing in the resolved migrations

### ISSUE THREAD

**Issue by jbellis** [atuinsh/atuin#1708]
Upgraded my ubuntu / arm64 install via cargo to 18.0.1 and this is the only message I get from atuin now. 
```
Error: migration 20230619235421 was previously applied but is missing in the resolved migrations

Location:
    /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/atuin-client-18.0.1/src/record/sqlite_store.rs:61:9
```

Unfortunately I do not know what the earlier version was, it doesn't seem to be preserved in the cargo registry cache.  Best guess from the time frame I last changed it is 14.0.1.

I did see another issue where someone ran into a similar error, but s/he ended up deleting history and starting over, which I would prefer to avoid.

On a related note, perhaps it would be a good idea to add an Upgrading section to the docs featuring "here's how to export your history before upgrading, just in case."  https://github.com/atuinsh/atuin/issues/1073#issuecomment-1912997953

**Comment by ellie** [comment]
Ah, sorry about that

20230619235421 only ever existed on `main` and was not released, did you ever build from source or run from `main`? I test migrations a whole bunch between versions to ensure that this doesn't happen, so would be super worried if this happened otherwise.

You can see that migration added here:

https://github.com/atuinsh/atuin/commit/f341c4bb7e2a81ad4e19a45d522fc617c97eda83

and deleted here:

https://github.com/atuinsh/atuin/commit/97e24d0d41bb743833e457de5ba49c5c233eb3b3

Where it was never released. 

Unfortunately this issue is a possibility if you run the bleeding edge, but not if you stick to tagged releases.

Anyway, this is a migration for the record store - prior to v18, the record store was not used for history (and even after v18, is opt-in). Historically, it has only been used for the `kv` store

If you haven't used the kv store, and you haven't switched to v2 sync, you're safe to delete `~/.local/share/atuin/records.db*` (note the *). This will not touch your history, which is in `~/.local/share/atuin/history.db`. 

_Otherwise_, running 

```
delete from _sqlx_migrations where version=20230619235421;
```

Should clear up the error. You're probably better to delete the database though.

--- 

For anyone finding this from Google/etc, post v18. _Do not delete records.db_, this advice applies purely to @jbellis' situation.

**Comment by jbellis** [comment]
I think I did install from source on this machine, now that you mention it.  (That would explain why it's not in cargo cache.)

I've never used the kv store so I went with option 1.  Problem solved.  Thanks!

**Comment by ellie** [comment]
Great! Glad you got it sorted 🙏
