### ISSUE TITLE
Sync error decoding response body: expected value at line 1 column 1

### ISSUE THREAD

**Issue by wudi** [atuinsh/atuin#1786]
Thanks the awesome Atuin!

Today i upgrade the new version 18.0.2 at both client and server side
But occur error below:

Mode: Self Hostd

## Client
```
(base) ➜  ~ atuin --version
atuin 18.0.2
(base) ➜  ~
(base) ➜  ~ atuin sync
Error: error decoding response body: expected value at line 1 column 1

Caused by:
    expected value at line 1 column 1

Location:
    /private/tmp/atuin-20240226-5245-z9ks0z/atuin-18.0.2/atuin-client/src/api_client.rs:161:21
```

## Server

```
docker exec -it atuin-atuin-1 atuin --version
atuin 18.0.2


docker inspect atuin-atuin-1 | jq '.[0].Config.Image'
"ghcr.io/atuinsh/atuin:cf09464"
```

**Comment by wudi** [comment]
I've fixed it!

Here the reason:
Atuin client send too large body more than Cloudflare default max size 100m  and Nginx default 1m.
Client got 413 status response.

But client do not show the HTTP status 413. Use JSON deocde directly code as below.

https://github.com/atuinsh/atuin/blob/94c85c31891c154d984f41a82401e0a7f782722e/atuin-client/src/api_client.rs#L160-L162

So, recommended to include the HTTP response status code in the error message. @ellie

**Comment by wudi** [comment]
Cloudflare Free plan upload limits: https://developers.cloudflare.com/cache/concepts/default-cache-behavior/#upload-limits

**Comment by pontusk** [comment]
I'm having this same issue. I would like to request that the error message better reflect what the JSON error response says, so that I can debug this on my server. I have logs set up and they say `Shutting down gracefully ...`. I'm drawing a blank on how to find the cause. 

Running `ATUIN_LOG=debug atuin sync -f` on the client tells me the body is 166 bytes. I did increase the Nginx limit, but there might be some other limit that causes this. Still, a better error message would be helpful.

**Comment by MrCaturdayNight** [comment]
This worked for me. Thanks @wudi 

I added this to my server entry for atuin in nginx. All is well now.

client_max_body_size 10M;
