### ISSUE TITLE
[Bug]: Out of disk space makes atuin unusable

### ISSUE THREAD

**Issue by tripleo1** [atuinsh/atuin#1886]
### What did you expect to happen?

`atuin` should proceed as usual.

### What happened?

`atuin` is not able to read/write config file, and so `bash` does not work right.

### Atuin doctor output

```yaml
...
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tessus** [comment]
Hmm, I don't think this is something that can be fixed by atuin. If there's no space on the filesystem, there are many other weird side effects that are worse than atuin not working.

You can't run any commands that use the filesystem in write mode. But even some commands that only read the filesystem use a RW filepointer which could result in the said command not working.
Basically the entire OS is stuck at that point.

When there is no space on the filesystem you have to free up space, otherwise atuin not working is the least of your problems. Why would you want to record commands, if you can't issue any commands?

**Comment by tripleo1** [comment]
If you cannot issue commands, you cannot record commands.

**Comment by ellie** [comment]
To clarify - does Atuin stop you from issuing commands at all, or is the problem that Atuin does not function?

The latter would be expected behaviour, as there's not much we can do when your system is out of disk space.

**Comment by tripleo1** [comment]
Expected behavior:

that Atuin would not attempt to write to the disk if it reports lack of
free space.

**Comment by tripleo1** [comment]
> Running out of disk is a pretty severe event that should be avoided

I don't understand what this means.

Feel free to close.

**Comment by linuxissuper** [comment]
I know this an old closed Issue but I just explain my use case   

Sometimes when I'm working on my server the disc becomes full and I get various errors   
When this happens I want to open my shell history and look for a command that frees some space   
but because atuin cannot function in read only mode, I cannot look for the command   
  
I think it would be nice, if atuin would still show the history and allowed for selecting commands  
any changes to the history would obviously not be written, but that's okay
