### ISSUE TITLE
Is there a way to control the number of listings I see in the search UI?

### ISSUE THREAD

**Issue by heeseon87** [atuinsh/atuin#2424]
The count in the top right corner of the UI is over 3000, but the history I can see in the list seems to be only the last month or so.
Is there a way to control the number of listings I see in the search UI?
I don't want to use the `history` command, I just want to navigate with the arrow up keys.

**Comment by ellie** [comment]
Not at the moment! 

We actually hardcode the initial listing to be 200 entries:

https://github.com/atuinsh/atuin/blob/5c29057e9ac8af4cb94edd0819057e2b2dd34557/crates/atuin/src/command/client/search/engines.rs#L38

This is for a few reasons

1. We'd like to keep the initial time to open the TUI nice and low
2. Instead of spending time scrolling to find what you want, we should optimize search so that it's easier to search for what you need

Is there any reason you're not just searching for the command? (just want to understand the use case better)

**Comment by heeseon87** [comment]
Just because it's more convenient.

**Comment by ellie** [comment]
I'm not sure the search UI is good for what you want then. If you'd like to browse your history, `atuin history list` will just dump it all to the screen for you to scroll through
