### ISSUE TITLE
[Feature]: Git as an Alternative Backend 🧙

### ISSUE THREAD

**Issue by metaory** [atuinsh/atuin#2462]
## Use Git as a backend

🔻 Avoid the mental burden of additional infra

🔻 Regardless of how or who manages it !
 
🔹 An opportunistic deferred 
🔹 background sync directly with 
🔹 user private git upstream

As simple as committing the db to user's private git repo

🔸🔸
- Vendor lock-in free
- Version-controlled
- Secure & decentralized
- Opens integration opportunities
- Simplify without infra related pieces

**Comment by ellie** [comment]
I'm afraid it's not actually that simple

What happens if two machines are offline for a while, the databases diverge, and then they both try to push to git?

In general, how do we handle forks in history + ensure it is reconciled properly? We have multiple writers that can go offline for any period of time, and need to eventually become consistent. 

Our sync is essentially a specialised form of a CRDT, which git isn't really a good backend for.

Additionally, git isn't really meant for storing large binary blobs, which is exactly what this would be doing

**Comment by metaory** [comment]
> What happens if two machines are offline for a while, the databases diverge, and then they both try to push to git?

Automated git conflict resolution is quite simple when you control all commiters,

---

> In general, how do we handle forks in history + ensure it is reconciled properly?

Could be one linear history with a strongly defined git flow strategy

**Since our app is the only type of writer** there be, 
Means we control all entrypoints, 

---

> We have multiple writers that can go offline for any period of time, and need to eventually become consistent.

A solved problem, there are projects in similar directions,

[github.com/hypercore](https://github.com/holepunchto/hypercore) 

---

> Our sync is essentially a specialised form of a CRDT, which git isn't really a good backend for.

history is typically append-only

_potentially with some meta files_

---

> Additionally, git isn't really meant for storing large binary blobs, which is exactly what this would be doing

we are doing sth wrong if we are storing large binary blobs for this tbh, so LFS probably won't even be needed,,

---

Final word, 

We are storing command history, not financial transactions, 

For some it's an upgrade from the local **.histfile** to 

1. a simple git backed storage

2. Hosted API + AUTH + SQLite + PostgreSQL + k8s + ...
 
...

nvm

🔻Thanks!!
