### ISSUE TITLE
Interactive deletion

### ISSUE THREAD

**Issue by SuperSandro2000** [atuinsh/atuin#854]
``atuin search --delete -i`` should work as an interactive deletion.
Right now the ``--delete`` argument is ingored.

**Comment by manfredlotz** [comment]
From my user's point of view: As it was a bit complicated to implement the deletion feature (because atuin can sync the history over systems) it was very important to implement it at all and thus to be able to use it from the command line.

So, I guess that interactive deletion will be implemented finally but it may take some time.
