### ISSUE TITLE
Error: error returned from database: (code: 11) database disk image is malformed

### ISSUE THREAD

**Issue by hukacode** [atuinsh/atuin#975]
Hello,

I recently got this error. How do I fix it?
```
Error: error returned from database: (code: 11) database disk image is malformed

Caused by:
    (code: 11) database disk image is malformed

Location:
    atuin/src/command/client.rs:50:22
```

**Comment by kraftnix** [comment]
I ran into the same issue, I had to restore the atuin database at `~/.local/share/atuin` to a version from a snapshot a few hours before to get it working again.

**Comment by conradludgate** [comment]
My guess is that either
1. Sqlite is broken (quite unlikely)
2. Atuin was exited ungracefully and libsqlite was interrupted in a bad place

**Comment by DavidMChan** [comment]
I also ran into this issue, though likely because I'm running atuin on a NFS-shared home drive. It seems like several atuin processes on different machines managing the same local DB leads to issues. 

Was able to fix, but not restore entirely, by running:
```
rm ~/.local/share/atuin/history.db*
rm ~/.local/share/atuin/records.db*
```

Though I'd love to know if there's a more graceful way to do this (ideally one without losing local shell history).

**Comment by xvello** [comment]
Heya @DavidMChan: as discussed in https://github.com/atuinsh/atuin/issues/2125 and mentioned [in the docs](https://docs.atuin.sh/known-issues/), storing the Atuin database on a networked filesystem is not supported as it leads to lock issues and data corruption. 

AFAIK @ellie has no plan to change this situation in the near future, as it comes from a limitation in sqlite itself. Since the original reporter didn't provide more information, I think it's safe to close this issue.

**Comment by ellie** [comment]
That's right, thanks @xvello 

Without significant changes we are unable to support running on NFS. While it may work fine for a while, eventually it will probably stop working. This is due to a NFS limitation affecting SQLite.
